services:
  - type: web
    name: ar-jewelry
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
